/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.woroud;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

/**
 *
 * @author Woroud Fouleh
 */
public class Addemp1 extends javax.swing.JFrame {

    /**
     * Creates new form Addemp
     */
    public Addemp1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Pno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        passs = new javax.swing.JTextField();
        role = new javax.swing.JComboBox<>();
        gender = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        streett = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        Addemp2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add new Employee");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 606, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("First name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 81, -1, 29));
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 85, 140, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Last name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 81, -1, 29));
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 85, 155, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("ID:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 116, 28, 29));
        getContentPane().add(Pno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 140, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Password:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 116, -1, 29));
        getContentPane().add(passs, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 123, 155, -1));

        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Manager", "Secretary", "Accountant", "Vendor" }));
        getContentPane().add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 150, 20));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Female", "Male" }));
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 170, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Gender:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 151, 63, 29));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Age:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 42, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("Role:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 151, 71, 29));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("City:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 216, 38, 29));
        getContentPane().add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 91, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setText("Street:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, 29));
        getContentPane().add(streett, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 91, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setText("Phone  number:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 29));
        getContentPane().add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 100, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 204));
        jLabel12.setText("Salary:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 50, 29));
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 220, 100, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 204));
        jLabel13.setText("Address:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 200, -1, 29));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 123, 140, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 204));
        jLabel14.setText("Email:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, 29));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 140, -1));

        Addemp2.setBackground(new java.awt.Color(0, 51, 153));
        Addemp2.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        Addemp2.setForeground(new java.awt.Color(255, 255, 255));
        Addemp2.setText("Add");
        Addemp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Addemp2MouseClicked(evt);
            }
        });
        Addemp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Addemp2ActionPerformed(evt);
            }
        });
        getContentPane().add(Addemp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 110, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Addemp2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Addemp2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Addemp2MouseClicked

    private void Addemp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Addemp2ActionPerformed
         try{
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             
            String url="jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con1 =DriverManager.getConnection(url,"c##woroud","123456") ;
            Statement st1 = con1.createStatement();
            
            String str="insert into EMPLOYEE values('"+this.id.getText()+"','"+this.fname.getText()+"','"+this.lname.getText()+"','"+this.streett.getText()+"','"+this.age.getText()+"','"+this.Pno.getText()+"','"+this.salary.getText()+"','"+this.role.getSelectedItem().toString()+"','"+this.gender.getSelectedItem().toString()+"','"+this.email.getText()+"','"+this.passs.getText()+"','"+this.city.getText()+"')";
            st1.executeUpdate(str);
            
            new Admin1().setVisible(true);
            con1.commit();
            con1.close();
           
           }
           catch(Exception e)
           {
               System.out.println(e.getMessage());
           }
        
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_Addemp2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addemp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addemp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addemp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addemp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addemp1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addemp2;
    private javax.swing.JTextField Pno;
    private javax.swing.JTextField age;
    private javax.swing.JTextField city;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField passs;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JTextField salary;
    private javax.swing.JTextField streett;
    // End of variables declaration//GEN-END:variables
}
