/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.woroud;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.datasource.OracleDataSource;

/**
 *
 * @author Woroud Fouleh
 */
public class CATEGORIES extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public CATEGORIES() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        category2 = new javax.swing.JLabel();
        logoutt = new javax.swing.JLabel();
        category22 = new javax.swing.JLabel();
        profilee2 = new javax.swing.JLabel();
        CATNAME = new javax.swing.JTextField();
        catID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CATTAB = new javax.swing.JTable();
        ADDCAT = new javax.swing.JButton();
        DELETECAT = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        PRODID = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PRODTAB = new javax.swing.JTable();
        ADDPROD = new javax.swing.JButton();
        DELETEPROD = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        PRODNAME = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        CATIDP = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        PRICE = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        DETAILS = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        BRAND = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        searchcat = new javax.swing.JButton();
        searchprod = new javax.swing.JButton();
        catupdate = new javax.swing.JButton();
        produpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(9, 72, 146));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\pic\\pic\\icon1 (1).png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CATEGORIES");

        jLabel17.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Products");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(300, 300, 300)
                .addComponent(jLabel17)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel17))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 70));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        category2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\pic\\pic\\cat (1).jpg")); // NOI18N
        jPanel2.add(category2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 70, 60));

        logoutt.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\pic\\pic\\exit.jpg")); // NOI18N
        logoutt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logouttMouseClicked(evt);
            }
        });
        jPanel2.add(logoutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 50, 50));

        category22.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\pic\\pic\\product (1).jpg")); // NOI18N
        jPanel2.add(category22, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 246, 70, 50));

        profilee2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\pic\\pic\\Employee (2).png")); // NOI18N
        profilee2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilee2MouseClicked(evt);
            }
        });
        jPanel2.add(profilee2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 70, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 70, 570));

        CATNAME.setToolTipText("");
        CATNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CATNAMEActionPerformed(evt);
            }
        });
        getContentPane().add(CATNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 150, 30));

        catID.setToolTipText("");
        catID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catIDActionPerformed(evt);
            }
        });
        getContentPane().add(catID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 150, 30));

        jLabel13.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 153));
        jLabel13.setText("Category Name:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 160, 20));

        jLabel14.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 153));
        jLabel14.setText("Category ID:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 150, 30));

        CATTAB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category Name", "Category ID"
            }
        ));
        jScrollPane1.setViewportView(CATTAB);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 390, 270));

        ADDCAT.setBackground(new java.awt.Color(0, 51, 153));
        ADDCAT.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        ADDCAT.setForeground(new java.awt.Color(255, 255, 255));
        ADDCAT.setText("Add new Category");
        ADDCAT.setToolTipText("");
        ADDCAT.setActionCommand("");
        ADDCAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDCATActionPerformed(evt);
            }
        });
        getContentPane().add(ADDCAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 230, 30));

        DELETECAT.setBackground(new java.awt.Color(0, 51, 153));
        DELETECAT.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        DELETECAT.setForeground(new java.awt.Color(255, 255, 255));
        DELETECAT.setText("Delete a Category");
        DELETECAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETECATActionPerformed(evt);
            }
        });
        getContentPane().add(DELETECAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, 230, 30));

        jLabel12.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 153));
        jLabel12.setText("Insert values to add:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, 30));

        PRODID.setToolTipText("");
        PRODID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRODIDActionPerformed(evt);
            }
        });
        getContentPane().add(PRODID, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 150, 30));

        jLabel16.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 153));
        jLabel16.setText("Product ID:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 150, 30));

        PRODTAB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product name", "Product ID", "Price", "Brand", "Details", "CAT ID"
            }
        ));
        jScrollPane2.setViewportView(PRODTAB);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 570, 270));

        ADDPROD.setBackground(new java.awt.Color(0, 51, 153));
        ADDPROD.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        ADDPROD.setForeground(new java.awt.Color(255, 255, 255));
        ADDPROD.setText("Add new Product");
        ADDPROD.setToolTipText("");
        ADDPROD.setActionCommand("");
        ADDPROD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDPRODActionPerformed(evt);
            }
        });
        getContentPane().add(ADDPROD, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 560, 230, 30));

        DELETEPROD.setBackground(new java.awt.Color(0, 51, 153));
        DELETEPROD.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        DELETEPROD.setForeground(new java.awt.Color(255, 255, 255));
        DELETEPROD.setText("Delete a Product");
        DELETEPROD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEPRODActionPerformed(evt);
            }
        });
        getContentPane().add(DELETEPROD, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 600, 230, 30));

        jLabel18.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 153));
        jLabel18.setText("Insert values to add:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, -1, -1));

        PRODNAME.setToolTipText("");
        PRODNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRODNAMEActionPerformed(evt);
            }
        });
        getContentPane().add(PRODNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 150, 30));

        jLabel19.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 153));
        jLabel19.setText("Product Name:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 160, -1));

        CATIDP.setToolTipText("");
        CATIDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CATIDPActionPerformed(evt);
            }
        });
        getContentPane().add(CATIDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 150, 30));

        jLabel21.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 51, 153));
        jLabel21.setText("Cat_ID:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 150, 30));

        PRICE.setToolTipText("");
        PRICE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRICEActionPerformed(evt);
            }
        });
        getContentPane().add(PRICE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 110, 150, 30));

        jLabel22.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 51, 153));
        jLabel22.setText("Price:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 110, 160, -1));

        DETAILS.setToolTipText("");
        DETAILS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DETAILSActionPerformed(evt);
            }
        });
        getContentPane().add(DETAILS, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 150, 150, 100));

        jLabel23.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 51, 153));
        jLabel23.setText("Details:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, 160, -1));

        BRAND.setToolTipText("");
        BRAND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRANDActionPerformed(evt);
            }
        });
        getContentPane().add(BRAND, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, 150, 30));

        jLabel24.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 51, 153));
        jLabel24.setText("Brand:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 150, 30));

        searchcat.setBackground(new java.awt.Color(0, 51, 153));
        searchcat.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        searchcat.setForeground(new java.awt.Color(255, 255, 255));
        searchcat.setText("Search");
        searchcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchcatActionPerformed(evt);
            }
        });
        getContentPane().add(searchcat, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, 100, -1));

        searchprod.setBackground(new java.awt.Color(0, 51, 153));
        searchprod.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        searchprod.setForeground(new java.awt.Color(255, 255, 255));
        searchprod.setText("Search");
        searchprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchprodActionPerformed(evt);
            }
        });
        getContentPane().add(searchprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 560, 100, -1));

        catupdate.setBackground(new java.awt.Color(0, 51, 153));
        catupdate.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        catupdate.setForeground(new java.awt.Color(255, 255, 255));
        catupdate.setText("Update");
        catupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catupdateActionPerformed(evt);
            }
        });
        getContentPane().add(catupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 600, 100, 30));

        produpdate.setBackground(new java.awt.Color(0, 51, 153));
        produpdate.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        produpdate.setForeground(new java.awt.Color(255, 255, 255));
        produpdate.setText("Update");
        produpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produpdateActionPerformed(evt);
            }
        });
        getContentPane().add(produpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 600, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void catIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catIDActionPerformed

    private void CATNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CATNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CATNAMEActionPerformed

    private void PRODIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRODIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRODIDActionPerformed

    private void PRODNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRODNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRODNAMEActionPerformed

    private void CATIDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CATIDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CATIDPActionPerformed

    private void PRICEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRICEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRICEActionPerformed

    private void DETAILSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DETAILSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DETAILSActionPerformed

    private void ADDPRODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDPRODActionPerformed
       try{
             DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             
            String url="jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con6 =DriverManager.getConnection(url,"c##woroud","123456") ;
            Statement st1 = con6.createStatement();
            
            String str="insert into PRODUCT values('"+PRODID.getText()+"','"+PRICE.getText()+"','"+BRAND.getText()+"','"+DETAILS.getText()+"','"+PRODNAME.getText()+"','"+CATIDP.getText()+"')";
            st1.executeUpdate(str);
            DefaultTableModel tblmodel=(DefaultTableModel)PRODTAB.getModel();
            tblmodel.setRowCount(0);
            ResultSet rs = st1.executeQuery("SELECT * FROM PRODUCT");
            while(rs.next())
            {
                String PID1= rs.getString("PID");
                String NAME1= rs.getString("NAME");
                String BRAND1= rs.getString("BRAND");
                String PRICE1= rs.getString("PRICE");
                String DETAILS1= rs.getString("DETAILS");
                String CAT_ID1= rs.getString("CAT_ID");
                
                
                
                String PRODdata []={NAME1,PID1,PRICE1,BRAND1,DETAILS1,CAT_ID1};
                //DefaultTableModel tblmodel=(DefaultTableModel)PRODTAB.getModel();
                tblmodel.addRow(PRODdata);
                
            }
            
            con6.commit();
            con6.close();
           
           }
           catch(Exception e)
           {
               System.out.println(e.getMessage());
           }
        



// TODO add your handling code here:
    }//GEN-LAST:event_ADDPRODActionPerformed

    private void ADDCATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDCATActionPerformed
       try{
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             
            String url="jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con3 =DriverManager.getConnection(url,"c##woroud","123456") ;
            Statement st1 = con3.createStatement();
            
            String str="insert into product_categories values('"+catID.getText()+"','"+CATNAME.getText()+"')";
            st1.executeUpdate(str);
            DefaultTableModel tblmodel=(DefaultTableModel)CATTAB.getModel();
            tblmodel.setRowCount(0);
            ResultSet rs = st1.executeQuery("SELECT * FROM PRODUCT_CATEGORIES");
            while(rs.next())
            {
                String CATID= rs.getString("CAT_ID");
                String Name= rs.getString("NAME");
                
                
                
                String empdata []={Name,CATID};
                
                tblmodel.addRow(empdata);
                
            }
            con3.commit();
            con3.close();
           
           }
           catch(Exception e)
           {
               System.out.println(e.getMessage());
           }
        














// TODO add your handling code here:
    }//GEN-LAST:event_ADDCATActionPerformed

    private void BRANDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRANDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BRANDActionPerformed

    private void profilee2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilee2MouseClicked
this.setVisible(false);
new Admin1().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_profilee2MouseClicked

    private void logouttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logouttMouseClicked
this.setVisible(false);
new First_page().setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_logouttMouseClicked

    private void searchcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchcatActionPerformed
       try{
         DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             
            String url="jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con2 =DriverManager.getConnection(url,"c##woroud","123456") ;
            Statement st = con2.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM PRODUCT_CATEGORIES");
            while(rs.next())
            {
                String CATID= rs.getString("CAT_ID");
                String Name= rs.getString("NAME");
                
                
                
                String empdata []={Name,CATID};
                DefaultTableModel tblmodel=(DefaultTableModel)CATTAB.getModel();
                tblmodel.addRow(empdata);
                
            }
            con2.commit();
            con2.close();
                   
           }
           catch(Exception e)
           {
               System.out.println(e.getMessage());
           }
        





// TODO add your handling code here:
    }//GEN-LAST:event_searchcatActionPerformed

    private void DELETECATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETECATActionPerformed
        
try{
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             
            String url="jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con12 =DriverManager.getConnection(url,"c##woroud","123456") ;
            Statement st = con12.createStatement();
            int x=CATTAB.getSelectedRow();
            String idd1=CATTAB.getModel().getValueAt(x, 1).toString();
            String del="delete from PRODUCT_CATEGORIES where cat_id= "+idd1;
            st.executeQuery(del);
            ResultSet rs = st.executeQuery("SELECT * FROM PRODUCT_CATEGORIES");
             DefaultTableModel tblmodel=(DefaultTableModel)CATTAB.getModel();
             tblmodel.setRowCount(0);
            while(rs.next())
            {
                String CAT_ID= rs.getString("CAT_ID");
                String CAT_NAME= rs.getString("NAME");
                
                
                
                String CATdata []={CAT_ID,CAT_NAME};
                //DefaultTableModel tblmodel=(DefaultTableModel)jTable1.getModel();
                tblmodel.addRow(CATdata);
                
            }
            tblmodel.removeRow(CATTAB.getSelectedRow());
            con12.commit();
            con12.close();
                   
           }
           catch(Exception e)
           {
               System.out.println(e.getMessage());
           }


// TODO add your handling code here:
    }//GEN-LAST:event_DELETECATActionPerformed

    private void searchprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchprodActionPerformed
        try{
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             
            String url="jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con77 =DriverManager.getConnection(url,"c##woroud","123456") ;
            Statement st = con77.createStatement();
            //DefaultTableModel tblmodel=(DefaultTableModel)PRODTAB.getModel();
            ResultSet rs = st.executeQuery("SELECT * FROM PRODUCT");
            while(rs.next())
            {
                String PID1= rs.getString("PID");
                String NAME1= rs.getString("NAME");
                String BRAND1= rs.getString("BRAND");
                String PRICE1= rs.getString("PRICE");
                String DETAILS1= rs.getString("DETAILS");
                String CAT_ID1= rs.getString("CAT_ID");
                
                
                
                String PRODdata []={NAME1,PID1,PRICE1,BRAND1,DETAILS1,CAT_ID1};
                DefaultTableModel tblmodel=(DefaultTableModel)PRODTAB.getModel();
                tblmodel.addRow(PRODdata);
                
            }
            //tblmodel.removeRow(PRODTAB.getSelectedRow());
            con77.commit();
            con77.close();
                   
           }
           catch(Exception e)
           {
               System.out.println(e.getMessage());
           }











// TODO add your handling code here:
    }//GEN-LAST:event_searchprodActionPerformed

    private void DELETEPRODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEPRODActionPerformed
       try{
        DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             
            String url="jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con12 =DriverManager.getConnection(url,"c##woroud","123456") ;
            Statement st = con12.createStatement();
            int x=PRODTAB.getSelectedRow();
            String idd1=PRODTAB.getModel().getValueAt(x, 1).toString();
            String del="delete from PRODUCT where PID= "+idd1;
            st.executeQuery(del);
            ResultSet rs = st.executeQuery("SELECT * FROM PRODUCT");
             DefaultTableModel tblmodel=(DefaultTableModel)PRODTAB.getModel();
             tblmodel.setRowCount(0);
            while(rs.next())
            {
                String PID1= rs.getString("PID");
                String NAME1= rs.getString("NAME");
                String BRAND1= rs.getString("BRAND");
                String PRICE1= rs.getString("PRICE");
                String DETAILS1= rs.getString("DETAILS");
                String CAT_ID1= rs.getString("CAT_ID");
                
                
                
                String PRODdata []={NAME1,PID1,PRICE1,BRAND1,DETAILS1,CAT_ID1};
                //DefaultTableModel tblmodel=(DefaultTableModel)PRODTAB.getModel();
                tblmodel.addRow(PRODdata);
                
            }
            tblmodel.removeRow(PRODTAB.getSelectedRow());
            con12.commit();
            con12.close();
                   
           }
           catch(Exception e)
           {
               System.out.println(e.getMessage());
           }
                    
       


// TODO add your handling code here:
    }//GEN-LAST:event_DELETEPRODActionPerformed

    private void catupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catupdateActionPerformed
 try{
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             DefaultTableModel tblmodel=(DefaultTableModel)CATTAB.getModel();
            String url="jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con3 =DriverManager.getConnection(url,"c##woroud","123456") ;
            Statement st1 = con3.createStatement();
            int x=CATTAB.getSelectedRow();
            String id1=CATTAB.getModel().getValueAt(x, 1).toString();
            String namee=CATTAB.getModel().getValueAt(x, 0).toString();
            String str="update PRODUCT_CATEGORIES set CAT_ID='"+id1+"',NAME='"+namee+"' where CAT_ID='"+id1+"'";
            st1.executeUpdate(str);
           // DefaultTableModel tblmodel=(DefaultTableModel)CATTAB.getModel();
            tblmodel.setRowCount(0);
            ResultSet rs = st1.executeQuery("SELECT * FROM PRODUCT_CATEGORIES");
            while(rs.next())
            {
                String CATID= rs.getString("CAT_ID");
                String Name= rs.getString("NAME");
                
                
                
                String empdata []={Name,CATID};
                
                tblmodel.addRow(empdata);
                
            }
            con3.commit();
            con3.close();
           
           }
           catch(Exception e)
           {
               System.out.println(e.getMessage());
           }        
// TODO add your handling code here:
    }//GEN-LAST:event_catupdateActionPerformed

    private void produpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produpdateActionPerformed
try{
        DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             
            String url="jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con12 =DriverManager.getConnection(url,"c##woroud","123456") ;
            Statement st = con12.createStatement();
            int x=PRODTAB.getSelectedRow();
            String namee=PRODTAB.getModel().getValueAt(x, 0).toString();
            String idd=PRODTAB.getModel().getValueAt(x, 1).toString();
            String pricee=PRODTAB.getModel().getValueAt(x, 2).toString();
            String brandd=PRODTAB.getModel().getValueAt(x, 3).toString();
            String detailss=PRODTAB.getModel().getValueAt(x, 4).toString();
            String catid=PRODTAB.getModel().getValueAt(x, 5).toString();
            String del="update PRODUCT set PID='"+idd+"',NAME='"+namee+"',PRICE='"+pricee+"',BRAND='"+brandd+"',DETAILS='"+detailss+"',CAT_ID='"+catid+"'where PID='"+idd+"'";
            st.executeQuery(del);
            ResultSet rs = st.executeQuery("SELECT * FROM PRODUCT");
             DefaultTableModel tblmodel=(DefaultTableModel)PRODTAB.getModel();
             tblmodel.setRowCount(0);
            while(rs.next())
            {
                String PID1= rs.getString("PID");
                String NAME1= rs.getString("NAME");
                String BRAND1= rs.getString("BRAND");
                String PRICE1= rs.getString("PRICE");
                String DETAILS1= rs.getString("DETAILS");
                String CAT_ID1= rs.getString("CAT_ID");
                
                
                
                String PRODdata []={NAME1,PID1,PRICE1,BRAND1,DETAILS1,CAT_ID1};
                //DefaultTableModel tblmodel=(DefaultTableModel)PRODTAB.getModel();
                tblmodel.addRow(PRODdata);
                
            }
            //tblmodel.removeRow(PRODTAB.getSelectedRow());
            con12.commit();
            con12.close();
                   
           }
           catch(Exception e)
           {
               System.out.println(e.getMessage());
           }        
// TODO add your handling code here:
    }//GEN-LAST:event_produpdateActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CATEGORIES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CATEGORIES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CATEGORIES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CATEGORIES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CATEGORIES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDCAT;
    private javax.swing.JButton ADDPROD;
    private javax.swing.JTextField BRAND;
    private javax.swing.JTextField CATIDP;
    private javax.swing.JTextField CATNAME;
    private javax.swing.JTable CATTAB;
    private javax.swing.JButton DELETECAT;
    private javax.swing.JButton DELETEPROD;
    private javax.swing.JTextField DETAILS;
    private javax.swing.JTextField PRICE;
    private javax.swing.JTextField PRODID;
    private javax.swing.JTextField PRODNAME;
    private javax.swing.JTable PRODTAB;
    private javax.swing.JTextField catID;
    private javax.swing.JLabel category2;
    private javax.swing.JLabel category22;
    private javax.swing.JButton catupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logoutt;
    private javax.swing.JButton produpdate;
    private javax.swing.JLabel profilee2;
    private javax.swing.JButton searchcat;
    private javax.swing.JButton searchprod;
    // End of variables declaration//GEN-END:variables
}
