/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.woroud;

import javax.swing.JOptionPane;

/**
 *
 * @author TestEnv
 */
public class First_page extends javax.swing.JFrame {

    /**
     * Creates new form First_page
     */
    public First_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Managerlog = new javax.swing.JLabel();
        customerlog = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Managerlog.setBackground(new java.awt.Color(255, 255, 255));
        Managerlog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManagerlogMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ManagerlogMousePressed(evt);
            }
        });
        jPanel1.add(Managerlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 440, 280, 80));

        customerlog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerlogMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                customerlogMousePressed(evt);
            }
        });
        jPanel1.add(customerlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(847, 580, 320, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\woroud (2)\\woroud\\src\\main\\java\\com\\mycompany\\woroud\\WhatsApp Image 2022-12-07 at 1.06.02 AM.jpeg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 790));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerlogMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerlogMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerlogMousePressed

    private void customerlogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerlogMouseClicked
                    this.setVisible(false);
                    new NewJFrame().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_customerlogMouseClicked

    private void ManagerlogMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManagerlogMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManagerlogMousePressed

    private void ManagerlogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManagerlogMouseClicked
        // TODO add your handling code here:
        String resp = "Enter manager Password:";
        boolean d=false;
        while(!d){
            String input = JOptionPane.showInputDialog(null, resp);

            if (input.compareTo("123456") == 0){
                JOptionPane.showMessageDialog(null, "Correct!");
                d=true;
                this.setVisible(false);
                new Admin1().setVisible(true);
            }
            else
            JOptionPane.showMessageDialog(null, "Incorrect, please enter password again");

        }
    }//GEN-LAST:event_ManagerlogMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(First_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(First_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(First_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(First_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //initComponents();
                new First_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Managerlog;
    private javax.swing.JLabel customerlog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
